# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
#image: gradle:alpine

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
stages:
  - clean
  - prepare
  - build-publish

buildLinux64:
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.java.home=/vol/software/jvm/zulu14.29.23-ca-fx-jdk14.0.2-linux_x64"
  stage: build
  script:
    - gradle clean artifactoryPublish --refresh-dependencies
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
  tags:
    - artifactory
    - gradle
    - linux64
  only:
    refs:
      - master
    # stupid there is no exclude if only specific type was changed, so we have to use some heuristic to exclude README only changes
    # from pipeline
    changes:
      - "**/*.{java,gradle,properties,yml,tex,png,ico,json,xml,html,csv,tsv,py}"
      - "**/src/main/java/**/*"