# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: git.bio.informatik.uni-jena.de:5050/bioinf-mit/docker-images/ubuntu-zulu-fx-gradle:18.04-15.0.3-6.9

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
stages:
  - clean
  - prepare
  - build-publish

buildLinux64:
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  stage: build-publish
  script:
    - gradle clean artifactoryPublish --refresh-dependencies
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
  tags:
    - kubernetes
  only:
    refs:
      - master
    # stupid there is no exclude if only specific type was changed, so we have to use some heuristic to exclude README only changes
    # from pipeline
    changes:
      - "**/*.{java,gradle,properties,yml,tex,png,ico,json,xml,html,csv,tsv,py}"
      - "**/src/main/java/**/*"