# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: git.bio.informatik.uni-jena.de:5050/bioinf-mit/docker-images/ubuntu-zulu-fx-gradle:22.04-15.42.15-6.9.2-9
#git.bio.informatik.uni-jena.de:5050/bioinf-mit/docker-images/ubuntu-zulu-fx-gradle:18.04-15.0.3-6.9-5

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
stages:
  - clean
  - prepare
  - build-publish
  - downstream

buildLinux64:
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  stage: build-publish
  script:
    - gradle clean artifactoryPublish --refresh-dependencies -P "de.unijena.bioinf.build.artifactory.username=$ARTIFACTORY_USERNAME" -P "de.unijena.bioinf.build.artifactory.password=$ARTIFACTORY_TOKEN"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
  tags:
    - kubernetes
  only:
    refs:
      - master
      - stable
    # stupid there is no exclude if only specific type was changed, so we have to use some heuristic to exclude README only changes
    # from pipeline
    changes:
      - "**/*.{java,gradle,properties,yml,tex,png,ico,json,xml,html,csv,tsv,py}"
      - "**/src/main/java/**/*"

trigger_sirius_frontend:
  stage: downstream
  trigger:
    project: bioinf-mit/ms/sirius_frontend
    strategy: depend
    branch: $CI_COMMIT_REF_NAME
  only:
    refs:
      - master
      - stable